name: Generate & Publish Global RSS (lean)

on:
  schedule:
    - cron: '0 2 * * *'
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install minimal runtime deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install "aiohttp==3.11.18" "aiofiles==24.1.0" "pydantic>=1.10,<2"

      - name: Write custom config (genshin, starrail, honkai)
        run: |
          rm -f hoyolab-rss-feeds.toml
          {
            echo "[genshin]"
            echo 'feed.json.path = "genshin.json"'
            echo
            echo "[starrail]"
            echo 'feed.json.path = "starrail.json"'
            echo
            echo "[honkai]"
            echo 'feed.json.path = "honkai.json"'
          } >> hoyolab-rss-feeds.toml

      - name: Show config (sanity check)
        run: |
          echo "=== hoyolab-rss-feeds.toml ==="
          cat hoyolab-rss-feeds.toml
          echo "==============================="
          if grep -qi 'honkai3rd' hoyolab-rss-feeds.toml; then
            echo "::error ::Found invalid key 'honkai3rd' in config"; exit 1;
          fi

      - name: Generate aggregated feeds
        env:
          PYTHONPATH: src
        run: |
          mkdir -p public
          python -m hoyolabrssfeeds \
            --single-feed-path public/index.xml \
            --single-feed-format atom \
            --single-feed-title "Hoyolab - All Games" \
            --single-home-url "https://www.hoyolab.com/"
          python -m hoyolabrssfeeds \
            --single-feed-path public/index.json \
            --single-feed-format json \
            --single-feed-title "Hoyolab - All Games" \
            --single-home-url "https://www.hoyolab.com/"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
